version: '3.8'

services:
  # PostgreSQL Database only
  postgres:
    image: pgvector/pgvector:pg15
    container_name: cmg-postgres-minimal
    environment:
      POSTGRES_DB: context_memory_gateway
      POSTGRES_USER: cmg_user  
      POSTGRES_PASSWORD: cmg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis Cache only
  redis:
    image: redis:7-alpine
    container_name: cmg-redis-minimal
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local