# PostgreSQL Database Credentials
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL

HOST=${host}
PORT=${port}
DATABASE=${database}
USERNAME=${username}
PASSWORD=${password}

# Connection Pool
POOL_HOST=${pool_host}
POOL_PORT=${pool_port}

# SSL Configuration
SSL_MODE=${ssl_mode}

# Full Connection URL (for application use)
DATABASE_URL=${connection_url}

# Connection Examples:
# psql: psql "${connection_url}"
# Python: asyncpg.connect("${connection_url}")
# SQLAlchemy: create_async_engine("${connection_url}")

# Notes:
# - Use the connection pool (POOL_HOST/POOL_PORT) for application connections
# - Direct database connection (HOST/PORT) should only be used for admin tasks
# - Always use SSL in production (sslmode=require)

