# Qdrant Vector Database Credentials
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL

DROPLET_IP=${droplet_ip}
PRIVATE_IP=${private_ip}
RESERVED_IP=${reserved_ip}
LOAD_BALANCER_IP=${lb_ip}

# Connection URLs
HTTP_URL=${http_url}
GRPC_URL=${grpc_url}

# Health Check
HEALTH_URL=${http_url}/health

# API Examples:
# Health: curl ${http_url}/health
# Collections: curl ${http_url}/collections
# Create collection: curl -X PUT ${http_url}/collections/my_collection -H "Content-Type: application/json" -d '{"vectors": {"size": 1536, "distance": "Cosine"}}'

# Python Client:
# from qdrant_client import QdrantClient
# client = QdrantClient(host="${private_ip}", port=6333)

# Notes:
# - Use private IP for internal communication
# - HTTP API on port 6333, gRPC on port 6334
# - No authentication configured (use VPC security)
# - Data persisted to attached volume
# - Automatic backups via DigitalOcean snapshots

