# Redis Database Credentials
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL

HOST=${host}
PORT=${port}
PASSWORD=${password}

# Full Connection URL (for application use)
REDIS_URL=${connection_url}

# Connection Examples:
# redis-cli: redis-cli -h ${host} -p ${port} -a ${password}
# Python: redis.from_url("${connection_url}")
# Node.js: redis.createClient("${connection_url}")

# Notes:
# - Redis requires authentication in DigitalOcean managed service
# - Connection is encrypted in transit
# - Use connection pooling for high-traffic applications

