# DigitalOcean Container Registry Credentials
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL

REGISTRY_NAME=${registry_name}
ENDPOINT=${endpoint}
SERVER_URL=${server_url}

# Docker Commands:
# Login: doctl registry login
# Build: docker build -t ${server_url}/${registry_name}/app:latest .
# Push: docker push ${server_url}/${registry_name}/app:latest
# Pull: docker pull ${server_url}/${registry_name}/app:latest

# CI/CD Integration:
# Use 'doctl registry docker-config' to generate Docker config for CI/CD
# Or use DigitalOcean API tokens for programmatic access

# Notes:
# - Registry authentication is handled via doctl CLI
# - Use DigitalOcean API tokens in CI/CD pipelines
# - Images are automatically scanned for vulnerabilities
# - Garbage collection policies help manage storage costs

