# Application Secrets
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL
# Store this file securely and use it to configure your application

# OpenRouter API
OPENROUTER_API_KEY=${openrouter_api_key}

# Authentication
AUTH_API_KEY_SALT=${auth_api_key_salt}
JWT_SECRET_KEY=${jwt_secret_key}

# DigitalOcean Spaces
SPACES_ACCESS_KEY=${spaces_access_key}
SPACES_SECRET_KEY=${spaces_secret_key}

# Database Passwords
POSTGRES_PASSWORD=${postgres_password}
REDIS_PASSWORD=${redis_password}

# Optional Services
SENTRY_DSN=${sentry_dsn}

# Security Notes:
# - Rotate these secrets regularly
# - Use environment variables or secure secret management
# - Never commit secrets to version control
# - Limit access to this file (chmod 600)
# - Use different secrets for each environment

