# DigitalOcean Spaces Credentials
# Generated by Terraform - DO NOT COMMIT TO VERSION CONTROL

BUCKET_NAME=${bucket_name}
REGION=${region}
ENDPOINT=${endpoint}
ACCESS_KEY=${access_key}
SECRET_KEY=${secret_key}

# Public URLs
BUCKET_URL=${bucket_url}

# AWS SDK Configuration (Spaces is S3-compatible)
AWS_ACCESS_KEY_ID=${access_key}
AWS_SECRET_ACCESS_KEY=${secret_key}
AWS_ENDPOINT_URL=${endpoint}
AWS_REGION=${region}

# Usage Examples:
# AWS CLI: aws s3 ls s3://${bucket_name} --endpoint-url ${endpoint}
# Python boto3: boto3.client('s3', endpoint_url='${endpoint}', aws_access_key_id='${access_key}', aws_secret_access_key='${secret_key}')
# curl: curl -H "Authorization: AWS ${access_key}:signature" ${bucket_url}/path/to/file

# Notes:
# - Spaces is fully compatible with AWS S3 API
# - Use the endpoint URL for all API calls
# - CORS is configured for web access
# - Versioning is enabled for data protection

